name: AppCenter Login
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Set up AppCenter
        id: setUpAppCenter
        run: |
          script log.log
          npm install -g appcenter-cli
          exit
      - name: Running UITests
        id: runningUitests
        run: |
          grep -A 100 "To address all issues" log.log
          
