name: App Build And Full UITests - outfitter
on: 
  pull_request:
    types:
      - closed
    branches-ignore:
      - dev-greyhound 
      - test-greyhound
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Set up AppCenter
        id: setUpAppCenter
        run: |
          script log.log -—Å npm install appcenter-cli
      - name: Output
        id: runningUitests
        run: grep -A 100 "To address all issues" log.log
          
