name: AppCenter Login
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Set up AppCenter
        id: setUpAppCenter
        run: |
          npm install -g appcenter-cli
          ls -a | tee output.file
      - name: Running UITests
        id: runningUitests
        run: echo tail -n 8 output.file
          
