name: AppCenter Login
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Recorder
        id: record
        run: script log.log
      - name: Set up AppCenter
        id: setUpAppCenter
        run: npm install -g appcenter-cli
      - name: Write
        id: write
        run: exit
      - name: Output
        id: runningUitests
        run: grep -A 100 "To address all issues" log.log
          
