name: AppCenter Login
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Set up AppCenter
        id: setUpAppCenter
        run: |
          npm install -g appcenter-cli
          tee output.log
          pwd
      - name: Running UITests
        id: runningUitests
        run: cat output.log
          
